spring:
  profiles:
    active: prod
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB   # 파일 하나의 최대 크기
      maxRequestSize: 30MB # 한 번에 최대 업로드 가능 용량
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    root: info

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

management:
  endpoints:
    web:
      exposure:
        include: '*'   # 모든 actuator 엔드포인트 노출
  metrics:
    data:
      repository:
        autotime:
          enabled: true
  endpoint:
    loggers:
      access: read_only
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    description: |
      datasource:
        url: jdbc:postgresql://localhost:5432/discodeit
        driver-class-name: org.postgresql.Driver
        jpa: ddl-auto
      storage:
        type: local
        path: .discodeit/storage
      multipart:
        maxFileSize: 10MB
        maxRequestSize: 30MB
    "app version": 1.7.0
    "java version": 17
    "spring boot version": 3.4.0